#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034

# Patterns to exclude from linting, anything starting with this will be excluded
excluded_prefixes+=(
    cache/
    scripts/dead_code/
)

# Exclude specific files by specifying their entire filename as listed by 'olint'.
excludes+=(
    # broken and not used ATM, keep for later fixing
    items/external_tools/_mullvad_country.sh
)

#override_linter_cmd["shellcheck"]="shellcheck --external-sources=false -a -x --color=always -o all -e SC2250,SC2312"

override_linter_cmd["shellcheck"]="shellcheck --color=always -o warn,style -e SC2250,SC2312"

# override_linter_cmd["shellcheck"]="shellcheck -a --color=always -o warn,style -e SC2250,SC2312"
# 4m2s
# override_linter_cmd["shellcheck"]="shellcheck -a --color=always -o all -e SC2250,SC2312"
# 4m5s
# override_linter_cmd["shellcheck"]="shellcheck -a -x --color=always -o warn,style -e SC2250,SC2312"
# 4m4s

# Avioid getting codespell error for teh in scripts/utils/tmux.sh
_skip='./.git,./.mypy_cache,./cache,./scripts/dead_code'
override_linter_cmd["codespell"]="codespell -H -S '$_skip' -L teh"
