#!/bin/sh

[ "$1" = "set" ] && {
    export MENUS_PROFILING=0
    export TMUX_MENUS_NO_DISPLAY=0
    export TMUX_MENUS_FORCE_SILENT=3
}

echo "MENUS_PROFILING: $MENUS_PROFILING"
echo "TMUX_MENUS_NO_DISPLAY: $TMUX_MENUS_NO_DISPLAY"
echo "TMUX_MENUS_FORCE_SILENT: $TMUX_MENUS_FORCE_SILENT"
