#!/bin/sh

[ "$1" = "set" ] && {
    export MENUS_PROFILING=0
    export TMUX_MENUS_NO_DISPLAY=0
    export TMUX_MENUS_FORCE_SILENT=1
    export TMUX_MENU_HANDLER=0
}

echo "MENUS_PROFILING: $MENUS_PROFILING"
echo "TMUX_MENUS_NO_DISPLAY: $TMUX_MENUS_NO_DISPLAY"
echo "TMUX_MENUS_FORCE_SILENT: $TMUX_MENUS_FORCE_SILENT"
echo "TMUX_MENU_HANDLER: $TMUX_MENU_HANDLER"
