#!/bin/sh
#
#  Copyright (c) 2025: Jacob.Lundqvist@gmail.com
#  License: MIT
#
#  Part of https://github.com/jaclu/tmux-menus
#
#  Template used for additional_items/_index.sh
#

static_content() {
    set -- \
        0.0 M Left "Back to Main menu    $nav_home" main.sh \
        0.0 S \
        "ADDITIONAL_ITEMS_SPLITTER" # the list of additional items will be inserted here

    menu_generate_part 1 "$@"
}

#===============================================================
#
#   Main
#
#===============================================================

menu_name="Additional items index"

#  Full path to tmux-menux plugin
D_TM_BASE_PATH="$(dirname -- "$(dirname -- "$(realpath "$0")")")"

# shellcheck source=scripts/dialog_handling.sh
. "$D_TM_BASE_PATH"/scripts/dialog_handling.sh
